"use client";
import { useState } from "react";
import { api, shortAddress } from "../../lib/api";
import { Shell } from "../../components/shell";
import { Badge, Modal } from "../../components/ui";
import { Icon } from "../../components/icons";

type Result = { did?: string; wallet?: string; status?: string; roleCode?: number; documentHash?: string; tokenId?: string; exists?: boolean; burned?: boolean; owner?: string | null; metadataUri?: string; source?: string; verifiedAtBlock?: string; verified?: boolean; checkedAtBlock?: string };
export default function VerifyPage() {
  const [kind, setKind] = useState<"DID" | "ASSET" | "OWNERSHIP">("DID"); const [subject, setSubject] = useState(""); const [did, setDid] = useState(""); const [result, setResult] = useState<Result | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function verify(e: React.FormEvent) { e.preventDefault(); setBusy(true); setError(null); setResult(null); try { const path = kind === "DID" ? `/api/v1/verify/did/${encodeURIComponent(subject)}` : kind === "ASSET" ? `/api/v1/verify/assets/${encodeURIComponent(subject)}` : `/api/v1/verify/ownership/${encodeURIComponent(did)}/${encodeURIComponent(subject)}`; setResult((await api<Result>(path)).data); } catch (e) { setError(e instanceof Error ? e.message : "Verification failed"); } finally { setBusy(false); } }
  return <Shell title="Public verification" description="Read authoritative DID, asset and ownership proof without relying on local UI state."><div className="mx-auto max-w-3xl"><div className="card p-6"><div className="mb-6 flex items-start gap-3"><div className="rounded-lg border border-cyan/30 bg-cyan/10 p-3 text-cyan"><Icon name="shield" size={21}/></div><div><p className="font-semibold">Verify on-chain evidence</p><p className="mt-1 text-sm text-muted">Verification endpoints may read the configured chain directly and report the checked block.</p></div></div><div className="mb-5 grid grid-cols-3 gap-2">{(["DID", "ASSET", "OWNERSHIP"] as const).map((option) => <button key={option} className={`btn ${kind === option ? "btn-primary" : ""}`} onClick={() => { setKind(option); setResult(null); }}>{option}</button>)}</div><form className="space-y-4" onSubmit={verify}><label className="block"><span className="eyebrow">{kind === "DID" ? "DID" : "Token ID"}</span><input required className="field mt-1" value={subject} onChange={(e) => setSubject(e.target.value)} placeholder={kind === "DID" ? "did:example:…" : "1"}/></label>{kind === "OWNERSHIP" && <label className="block"><span className="eyebrow">Owner DID</span><input required className="field mt-1" value={did} onChange={(e) => setDid(e.target.value)} placeholder="did:example:…"/></label>}<button className="btn btn-primary w-full" disabled={busy}>{busy ? "Checking chain…" : "Verify evidence"}</button></form></div>{error && <div className="mt-4 rounded-lg border border-danger/40 bg-danger/10 p-4 text-sm text-danger">{error}</div>}{result && <ResultCard result={result}/>}</div></Shell>;
}
function ResultCard({ result }: { result: Result }) { const verified = result.verified ?? (result.status === "ACTIVE" || result.exists === true); return <div className="card mt-4 p-5"><div className="flex items-center justify-between"><p className="font-semibold">Verification result</p><Badge tone={verified ? "success" : "danger"}>{verified ? "VERIFIED" : "NOT VERIFIED"}</Badge></div><dl className="mt-5 grid gap-4 sm:grid-cols-2">{Object.entries(result).filter(([key]) => !["verified", "exists", "burned"].includes(key)).map(([key, value]) => <div key={key}><dt className="eyebrow">{key.replace(/[A-Z]/g, (x) => ` ${x}`).trim()}</dt><dd className="mt-1 break-all font-mono text-sm text-muted">{key === "wallet" || key === "owner" ? shortAddress(String(value)) : String(value ?? "—")}</dd></div>)}</dl></div>; }
