"use client";
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { api, formatDate, shortAddress } from "../../lib/api";
import type { Transaction } from "../../lib/types";
import { Shell } from "../../components/shell";
import { Badge, Modal } from "../../components/ui";
import { Icon } from "../../components/icons";

export default function TransactionsPage() { const [hash, setHash] = useState(""); const [transaction, setTransaction] = useState<Transaction | null>(null); const [error, setError] = useState<string | null>(null); const lookup = useMutation({ mutationFn: (value: string) => api<Transaction>(`/api/v1/transactions/${value}`), onSuccess: (r) => { setTransaction(r.data); setError(null); }, onError: (e) => setError(e instanceof Error ? e.message : "Transaction not found") }); return <Shell title="Transactions" description="Inspect submitted operations without resubmitting state-changing requests."><div className="mx-auto max-w-2xl"><div className="console-panel p-6"><p className="font-semibold">Transaction status</p><p className="mt-1 text-sm text-muted">Enter a canonical transaction hash returned by a write operation.</p><form className="mt-5 flex gap-2" onSubmit={(e) => { e.preventDefault(); lookup.mutate(hash); }}><input required pattern="0x[0-9a-fA-F]{64}" className="field font-mono" value={hash} onChange={(e) => setHash(e.target.value)} placeholder="0x…"/><button className="btn btn-primary whitespace-nowrap" disabled={lookup.isPending}>{lookup.isPending ? "Loading…" : "Refresh status"}</button></form></div>{error && <div className="mt-4 rounded-lg border border-danger/40 bg-danger/10 p-4 text-sm text-danger">{error}</div>}{transaction && <Modal title="Transaction lifecycle" onClose={() => setTransaction(null)}><div className="flex items-center justify-between"><span className="font-mono text-xs text-muted">{shortAddress(transaction.txHash)}</span><Badge tone={transaction.status === "CONFIRMED" ? "success" : transaction.status === "FAILED" ? "danger" : "warning"}>{transaction.status}</Badge></div><dl className="mt-5 space-y-3 text-sm"><div><dt className="eyebrow">Submitted</dt><dd className="mt-1">{formatDate(transaction.submittedAt)}</dd></div><div><dt className="eyebrow">Confirmed</dt><dd className="mt-1">{formatDate(transaction.confirmedAt)}</dd></div><div><dt className="eyebrow">Block</dt><dd className="mt-1">{transaction.blockNumber ?? "Pending"}</dd></div></dl>{transaction.errorMessage && <p className="mt-4 rounded-lg border border-danger/30 bg-danger/10 p-3 text-sm text-danger">{transaction.errorMessage}</p>}</Modal>}</div></Shell>; }
