"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, shortAddress } from "../../lib/api";
import type { Asset } from "../../lib/types";
import { Shell } from "../../components/shell";
import { Badge, Empty, ErrorCard, Loading, Modal, PermissionDenied } from "../../components/ui";
import { Icon } from "../../components/icons";
import { usePermissions } from "../../components/permissions";

export default function AssetsPage() {
  const [search, setSearch] = useState(""); const [showMint, setShowMint] = useState(false); const [notice, setNotice] = useState<string | null>(null); const client = useQueryClient();
  const permissions = usePermissions();
  const query = useQuery({ queryKey: ["assets"], queryFn: async () => (await api<Asset[]>("/api/v1/assets")).data });
  const rows = query.data?.filter((a) => `${a.tokenId} ${a.metadataUri} ${a.currentOwner?.address ?? ""}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  const burn = useMutation({ mutationFn: (tokenId: string) => api(`/api/v1/assets/${tokenId}`, { method: "DELETE", body: JSON.stringify({}) }), onSuccess: () => { setNotice("Burn transaction submitted; the asset remains until indexed."); client.invalidateQueries({ queryKey: ["assets"] }); }, onError: (e) => setNotice(e instanceof Error ? e.message : "Burn failed") });
  const mint = useMutation({ mutationFn: (body: { to: string; metadataUri: string; assetType: "DIGITAL" | "PHYSICAL" }) => api("/api/v1/assets", { method: "POST", body: JSON.stringify(body) }), onSuccess: () => { setShowMint(false); setNotice("Mint transaction submitted."); client.invalidateQueries({ queryKey: ["assets"] }); }, onError: (e) => setNotice(e instanceof Error ? e.message : "Mint failed") });
  return <Shell title="Assets" description="Track tokenized assets, ownership, metadata health and irreversible lifecycle actions." action={<button className="btn btn-primary" disabled={permissions.loading || !permissions.can("ASSET_MINT")} title={!permissions.loading && !permissions.can("ASSET_MINT") ? "Requires ASSET_MINT" : undefined} onClick={() => setShowMint(true)}><Icon name="plus" size={15}/>Mint asset</button>}>
    {notice && <div className="mb-4 flex items-center justify-between rounded-lg border border-warning/30 bg-warning/10 px-4 py-3 text-sm text-warning"><span>{notice}</span><button onClick={() => setNotice(null)}><Icon name="x" size={15}/></button></div>}
    {!permissions.loading && !permissions.can("ASSET_MINT") && <div className="mb-4"><PermissionDenied permission="ASSET_MINT"/></div>}
    <div className="command-bar mb-4 flex flex-wrap items-center gap-3 p-3"><div className="relative min-w-[220px] flex-1"><Icon name="search" size={15}/><input className="field pl-9" placeholder="Search token ID, URI or owner" value={search} onChange={(e) => setSearch(e.target.value)}/></div><Badge tone="info">{rows.length} indexed</Badge></div>
    {query.isLoading ? <Loading rows={5}/> : query.error ? <ErrorCard error={query.error} retry={() => query.refetch()}/> : !rows.length ? <Empty title="No assets found" description={search ? "Try another token ID or owner." : "Mint an asset or wait for the indexer to observe a mint event."}/> : <div className="console-panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-line/70 bg-surface/50 text-xs text-muted"><tr><th className="px-4 py-3 font-medium">Asset</th><th className="px-4 py-3 font-medium">Type</th><th className="px-4 py-3 font-medium">Owner</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 font-medium">Metadata URI</th><th className="px-4 py-3 font-medium">Action</th></tr></thead><tbody className="divide-y divide-line/60">{rows.map((asset) => <tr key={String(asset.tokenId)} className="hover:bg-surface/40"><td className="px-4 py-3 font-medium text-cyan">#{String(asset.tokenId)}</td><td className="px-4 py-3 text-muted">{asset.assetType ?? "—"}</td><td className="px-4 py-3 font-mono text-xs text-muted">{shortAddress(asset.currentOwner?.address)}</td><td className="px-4 py-3"><Badge tone={asset.status === "ACTIVE" ? "success" : "danger"}>{asset.status}</Badge></td><td className="max-w-[300px] truncate px-4 py-3 font-mono text-xs text-muted">{asset.metadataUri}</td><td className="px-4 py-3">{asset.status === "ACTIVE" && <button className="btn btn-danger px-2 py-1 text-xs" disabled={burn.isPending || !permissions.can("ASSET_BURN")} title={!permissions.can("ASSET_BURN") ? "Requires ASSET_BURN" : undefined} onClick={() => { if (window.confirm(`Burn token #${asset.tokenId}? This cannot be undone.`)) burn.mutate(String(asset.tokenId)); }}>Burn</button>}</td></tr>)}</tbody></table></div></div>}
    {showMint && <MintAsset onClose={() => setShowMint(false)} onSubmit={(body) => mint.mutate(body)} pending={mint.isPending}/>}
  </Shell>;
}
function MintAsset({ onClose, onSubmit, pending }: { onClose: () => void; onSubmit: (body: { to: string; metadataUri: string; assetType: "DIGITAL" | "PHYSICAL" }) => void; pending: boolean }) {
  const [body, setBody] = useState<{ to: string; metadataUri: string; assetType: "DIGITAL" | "PHYSICAL" }>({ to: "", metadataUri: "", assetType: "DIGITAL" });
  return <Modal title="Mint asset" onClose={onClose}><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); onSubmit(body); }}><label className="block"><span className="eyebrow">Recipient wallet</span><input required pattern="0x[0-9a-fA-F]{40}" className="field mt-1" value={body.to} onChange={(e) => setBody({ ...body, to: e.target.value })} placeholder="0x…"/></label><label className="block"><span className="eyebrow">Metadata URI</span><input required className="field mt-1" value={body.metadataUri} onChange={(e) => setBody({ ...body, metadataUri: e.target.value })} placeholder="ipfs://…"/></label><label className="block"><span className="eyebrow">Asset type</span><select className="field mt-1" value={body.assetType} onChange={(e) => setBody({ ...body, assetType: e.target.value as "DIGITAL" | "PHYSICAL" })}><option value="DIGITAL">Digital</option><option value="PHYSICAL">Physical</option></select></label><p className="rounded-lg border border-warning/30 bg-warning/10 p-3 text-xs text-warning">Metadata availability is checked by the backend. Minting submits an on-chain transaction.</p><button className="btn btn-primary w-full" disabled={pending}>{pending ? "Submitting…" : "Review and submit"}</button></form></Modal>;
}
