"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api, shortAddress, walletAddress } from "../../lib/api";
import type { Identity } from "../../lib/types";
import { Shell } from "../../components/shell";
import { Badge, Empty, ErrorCard, Loading, Modal, PermissionDenied } from "../../components/ui";
import { Icon } from "../../components/icons";
import { usePermissions } from "../../components/permissions";

export default function IdentitiesPage() {
  const [search, setSearch] = useState(""); const [showCreate, setShowCreate] = useState(false); const [selected, setSelected] = useState<Identity | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const permissions = usePermissions();
  const client = useQueryClient();
  const query = useQuery({ queryKey: ["identities"], queryFn: async () => (await api<Identity[]>("/api/v1/identities")).data });
  const rows = query.data?.filter((i) => `${i.did} ${walletAddress(i.wallet)}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  const action = useMutation({ mutationFn: ({ did, type }: { did: string; type: "revoke" | "restore" }) => api(`/api/v1/identities/${encodeURIComponent(did)}/${type}`, { method: "POST", body: JSON.stringify({}) }), onSuccess: (_, variables) => { setNotice(`Identity ${variables.type} transaction submitted.`); client.invalidateQueries({ queryKey: ["identities"] }); }, onError: (e) => setNotice(e instanceof Error ? e.message : "Action failed") });
  const create = useMutation({ mutationFn: (body: { wallet: string; did: string; roleCode: number; documentHash: string }) => api("/api/v1/identities", { method: "POST", body: JSON.stringify(body) }), onSuccess: () => { setShowCreate(false); setNotice("Identity transaction submitted."); client.invalidateQueries({ queryKey: ["identities"] }); }, onError: (e) => setNotice(e instanceof Error ? e.message : "Create failed") });
  return <Shell title="Identities" description="Manage DID registrations, wallet bindings, and lifecycle status." action={<button className="btn btn-primary" disabled={permissions.loading || !permissions.can("IDENTITY_CREATE")} title={!permissions.loading && !permissions.can("IDENTITY_CREATE") ? "Requires IDENTITY_CREATE" : undefined} onClick={() => setShowCreate(true)}><Icon name="plus" size={15}/>Create identity</button>}>
    {notice && <div className="mb-4 flex items-center justify-between rounded-lg border border-warning/30 bg-warning/10 px-4 py-3 text-sm text-warning"><span>{notice}</span><button onClick={() => setNotice(null)}><Icon name="x" size={15}/></button></div>}
    {!permissions.loading && !permissions.can("IDENTITY_CREATE") && <div className="mb-4"><PermissionDenied permission="IDENTITY_CREATE"/></div>}
    <div className="card mb-4 flex flex-wrap items-center gap-3 p-3"><div className="relative min-w-[220px] flex-1"><Icon name="search" size={15}/><input className="field pl-9" placeholder="Search DID or wallet" value={search} onChange={(e) => setSearch(e.target.value)}/></div><Badge tone="info">{rows.length} indexed</Badge></div>
    {query.isLoading ? <Loading rows={5}/> : query.error ? <ErrorCard error={query.error} retry={() => query.refetch()}/> : !rows.length ? <Empty title="No identities found" description={search ? "Try a different DID or wallet search." : "Create an identity or wait for the indexer to observe a registration."}/> : <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b border-line/70 bg-surface/50 text-xs text-muted"><tr><th className="px-4 py-3 font-medium">Identity</th><th className="px-4 py-3 font-medium">Wallet</th><th className="px-4 py-3 font-medium">Role code</th><th className="px-4 py-3 font-medium">Status</th><th className="px-4 py-3 font-medium">Document</th><th className="px-4 py-3 font-medium">Actions</th></tr></thead><tbody className="divide-y divide-line/60">{rows.map((identity) => <tr key={identity.did} className="hover:bg-surface/40"><td className="max-w-[280px] px-4 py-3"><button className="truncate text-left font-medium text-cyan hover:underline" onClick={() => setSelected(identity)}>{identity.did}</button></td><td className="px-4 py-3 font-mono text-xs text-muted">{shortAddress(walletAddress(identity.wallet))}</td><td className="px-4 py-3 text-muted">{identity.roleCode ?? "—"}</td><td className="px-4 py-3"><Badge tone={identity.status === "ACTIVE" ? "success" : "danger"}>{identity.status}</Badge></td><td className="max-w-[180px] truncate px-4 py-3 font-mono text-xs text-muted">{identity.documentHash ?? "—"}</td><td className="px-4 py-3"><button className={`btn ${identity.status === "ACTIVE" ? "btn-danger" : ""} px-2 py-1 text-xs`} disabled={action.isPending} onClick={() => action.mutate({ did: identity.did, type: identity.status === "ACTIVE" ? "revoke" : "restore" })}>{identity.status === "ACTIVE" ? "Revoke" : "Restore"}</button></td></tr>)}</tbody></table></div></div>}
    {showCreate && <CreateIdentity onClose={() => setShowCreate(false)} onSubmit={(body) => create.mutate(body)} pending={create.isPending}/>}
    {selected && <Modal title="Identity details" onClose={() => setSelected(null)}><dl className="space-y-3 text-sm"><div><dt className="eyebrow">DID</dt><dd className="mt-1 break-all font-mono">{selected.did}</dd></div><div><dt className="eyebrow">Wallet</dt><dd className="mt-1 font-mono">{walletAddress(selected.wallet) ?? "—"}</dd></div><div><dt className="eyebrow">Document hash</dt><dd className="mt-1 break-all font-mono text-muted">{selected.documentHash ?? "—"}</dd></div><div><dt className="eyebrow">Indexed block</dt><dd className="mt-1">{selected.lastChainBlock ?? "—"}</dd></div></dl></Modal>}
  </Shell>;
}
function CreateIdentity({ onClose, onSubmit, pending }: { onClose: () => void; onSubmit: (body: { wallet: string; did: string; roleCode: number; documentHash: string }) => void; pending: boolean }) {
  const [body, setBody] = useState({ wallet: "", did: "", roleCode: "3", documentHash: "" });
  return <Modal title="Create identity" onClose={onClose}><form className="space-y-4" onSubmit={(e) => { e.preventDefault(); onSubmit({ ...body, roleCode: Number(body.roleCode) }); }}><label className="block"><span className="eyebrow">Wallet address</span><input required pattern="0x[0-9a-fA-F]{40}" className="field mt-1" value={body.wallet} onChange={(e) => setBody({ ...body, wallet: e.target.value })} placeholder="0x…"/></label><label className="block"><span className="eyebrow">Canonical DID</span><input required className="field mt-1" value={body.did} onChange={(e) => setBody({ ...body, did: e.target.value })} placeholder="did:example:…"/></label><label className="block"><span className="eyebrow">Role code</span><input required type="number" min="0" max="255" className="field mt-1" value={body.roleCode} onChange={(e) => setBody({ ...body, roleCode: e.target.value })}/></label><label className="block"><span className="eyebrow">DID document hash</span><input required pattern="0x[0-9a-fA-F]{64}" className="field mt-1" value={body.documentHash} onChange={(e) => setBody({ ...body, documentHash: e.target.value })} placeholder="0x…"/></label><p className="rounded-lg border border-warning/30 bg-warning/10 p-3 text-xs text-warning">This submits an on-chain transaction. The API and contract remain authoritative.</p><button className="btn btn-primary w-full" disabled={pending}>{pending ? "Submitting…" : "Review and submit"}</button></form></Modal>;
}
